# Generated by Django 3.2.1 on 2021-05-16 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=100)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.program')),
            ],
        ),
    ]
