# Generated by Django 3.2.1 on 2021-06-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210603_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passwordConfirm',
            field=models.CharField(default='', max_length=100),
        ),
    ]
