# Generated by Django 3.2.1 on 2021-05-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210516_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program',
            new_name='course',
        ),
    ]
