# Generated by Django 3.2.1 on 2021-06-03 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_users_passwordconfirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='passwordConfirm',
        ),
    ]
