# Generated by Django 3.2.1 on 2021-05-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_program_program_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='course',
        ),
        migrations.AddField(
            model_name='program',
            name='course',
            field=models.ManyToManyField(to='myapp.Course'),
        ),
    ]
