# Generated by Django 3.2.1 on 2021-05-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210516_0820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Programs',
        ),
    ]
