# Generated by Django 3.2.1 on 2021-05-20 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_program_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programwithcourses',
            name='program_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.programs'),
        ),
    ]
