# Generated by Django 3.2.1 on 2021-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210520_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programwithcourses',
            name='course1',
        ),
        migrations.RemoveField(
            model_name='programwithcourses',
            name='course2',
        ),
        migrations.RemoveField(
            model_name='programwithcourses',
            name='course3',
        ),
        migrations.RemoveField(
            model_name='programwithcourses',
            name='course4',
        ),
        migrations.AddField(
            model_name='programwithcourses',
            name='courses',
            field=models.ManyToManyField(null=True, to='myapp.Course'),
        ),
    ]
