# Generated by Django 3.2.1 on 2021-05-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210520_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
        migrations.RemoveField(
            model_name='programwithcourses',
            name='courses',
        ),
        migrations.AddField(
            model_name='programwithcourses',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.course'),
        ),
    ]
